### ISSUE TITLE
Começando o Projeto

### ISSUE THREAD

**Issue by narcisista3g** [asa-inovacoes/onix-aircraft-api#1]

**Comment by narcisista3g** [comment]
# Criação do Projeto


__Objetivo dessa issue é as configurações básicas para iniciar o projeto como git flow, repositório, branchs e alguns arquivos padrão como git ignore e etc.__


### Informações extras da Issue

- [ ] Novo Recursos há uma das aplicações.
- [ ] Resolver um Problema existente.
- [ ] Melhoria de código.
- [X] Configuração do Repositório.
- [X] Configuração do Projeto.


## TO-DO

- [ ] Criar o repositório.
- [ ] Configurar o repositórios e algumas informações.
- [ ] Criar o arquivo de licença.
- [ ] Criar o arquivo de código de conduta.
- [ ] Criar o arquivo de segurança do projeto.
- [ ] Criar o arquivo de contribuidores do projeto.

![Brolly Gif Image](https://gifs.eco.br/wp-content/uploads/2022/07/gifs-do-broly-6.gif)
